name: Run Unit Server Tests

on: [pull_request]

jobs:
  run-unit-tests:
    name: Run Unit Server Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run test
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"
          CLIENT_URL: "http://localhost:5173"
          STRIPE_KEY: "key",
          PRICE_ID: "id",
          ENDPOINT_SECRET: "secret",
          EMAIL_USER: ${{ secrets.EMAIL_USER }},
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          PASSWORD_SECRET: "password"
