name: Run E2E Client Tests

on: [pull_request]

jobs:
  run-e2e-client-tests:
    name: Run E2E Client Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client

    container:
      image: mcr.microsoft.com/playwright:v1.46.1-jammy

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run your tests
        run: npx playwright test
        env:
          HOME: /root
