name: Run Unit Client Tests

on: [pull_request]

jobs:
  run-unit-tests:
    name: Run Unit Client Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm ci
      - run: npm run test
